openapi: 3.0.0
info:
  version: 0.1.0
  title: "MinRepo API"
  description: |
    Mini Maven repository and archiving server
  termsOfService: empty
  contact:
    name: yh.lee
    email: metalsm7@gmail.com
    url: https://mparang.com
  x-logo:
    # url: ''
    altText: "MinRepo"
servers:
  - url: http://localhost/v1
tags:
  - name: Manage
    description: |
      Manage
  - name: Maven
    description: |
      Maven Repo
  - name: Archive
    description: |
      Archieving
paths:
  /manage/auths:
    get:
      tags:
        - Manage
      operationId: GetAuths
      summary: Get Auth List
      description: |
        Get All Auth List
      parameters:
        - name: credential
          description: access_key
          in: header
          schema:
            type: string
    post:
      tags:
        - Manage
      operationId: AddAuth
      summary: Add Auth
      description: |
        Add Auth
      parameters:
        - name: credential
          description: access_key
          in: header
          schema:
            type: string
  /manage/auths/{access_key}:
    get:
      tagls:
        - Manage
  /{access_key}/archieve/{group_id_url_form}/{artifact_id}/{version}:
    post:
      tags:
        - Archive
      operationId: GetArchive
      summary: Get Archive File
      description: |
        Download archive file
      parameters:
        - name: access_key
          in: path

  /{access_key}/maven/{group_id}/{artifact_id}/maven-metadata.xml:
    get:
      tags:
        - Maven
      operationId: GetMavenRepo
      summary: Request Repo
      description: |
        maven repo 를 요청합니다.
      parameters:
        - name: repo
          in: path
          schema:
            type: string
  /{access_key}/maven/{group_id}/{artifact_id}/{version}/{artifact_id}.pom:
    get:
      tags:
        - Maven
  /{access_key}/maven/{group_id}/{artifact_id}/{version}/{artifact_id}.jar:
    get:
      tags:
        - Maven
      
